name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-version: ${{ secrets.CACHE_VERSION }}
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pkg-cache-${{ hashFiles('**/yarn.lock') }}-${{ env.cache-version }}
        restore-keys: |
          ${{ runner.os }}-pkg-cache-${{ hashFiles('**/yarn.lock') }}-
          ${{ runner.os }}-pkg-cache

    - name: Install dependencies
      run: yarn install

    # - name: Lint
    #   run: yarn lint

    - name: Test package
      run: yarn test

    - name: Type check
      run: yarn type-check

    # - name: Package building test
    #   run: yarn build
